
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JAZZY
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();

    }
    
    
        private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        setcolor(jPTab_bord);
        FormTAB tab = new FormTAB();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPTab_bord = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPLivre = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPEmprunt = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPMembre = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPReservation = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPSanctiom = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 100));

        jPTab_bord.setBackground(new java.awt.Color(255, 102, 0));
        jPTab_bord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPTab_bordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPTab_bordMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\ETUDE\\java\\BIBLIOTHEQUE3.0\\imageprojet\\tab_bord_16.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tableau de bord");

        javax.swing.GroupLayout jPTab_bordLayout = new javax.swing.GroupLayout(jPTab_bord);
        jPTab_bord.setLayout(jPTab_bordLayout);
        jPTab_bordLayout.setHorizontalGroup(
            jPTab_bordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTab_bordLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );
        jPTab_bordLayout.setVerticalGroup(
            jPTab_bordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPLivre.setBackground(new java.awt.Color(255, 102, 0));
        jPLivre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPLivreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPLivreMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\ETUDE\\java\\BIBLIOTHEQUE3.0\\imageprojet\\livre_16.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Livre");

        javax.swing.GroupLayout jPLivreLayout = new javax.swing.GroupLayout(jPLivre);
        jPLivre.setLayout(jPLivreLayout);
        jPLivreLayout.setHorizontalGroup(
            jPLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLivreLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPLivreLayout.setVerticalGroup(
            jPLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPEmprunt.setBackground(new java.awt.Color(255, 102, 0));
        jPEmprunt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPEmpruntMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPEmpruntMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\ETUDE\\java\\BIBLIOTHEQUE3.0\\imageprojet\\Emprunt_16.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Emprunt");

        javax.swing.GroupLayout jPEmpruntLayout = new javax.swing.GroupLayout(jPEmprunt);
        jPEmprunt.setLayout(jPEmpruntLayout);
        jPEmpruntLayout.setHorizontalGroup(
            jPEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpruntLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPEmpruntLayout.setVerticalGroup(
            jPEmpruntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPMembre.setBackground(new java.awt.Color(255, 102, 0));
        jPMembre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPMembreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPMembreMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\ETUDE\\java\\BIBLIOTHEQUE3.0\\imageprojet\\Membre_16.png")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Membres");

        javax.swing.GroupLayout jPMembreLayout = new javax.swing.GroupLayout(jPMembre);
        jPMembre.setLayout(jPMembreLayout);
        jPMembreLayout.setHorizontalGroup(
            jPMembreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMembreLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPMembreLayout.setVerticalGroup(
            jPMembreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPReservation.setBackground(new java.awt.Color(255, 102, 0));
        jPReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPReservationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPReservationMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\ETUDE\\java\\BIBLIOTHEQUE3.0\\imageprojet\\reservatiom_16.png")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reservation");

        javax.swing.GroupLayout jPReservationLayout = new javax.swing.GroupLayout(jPReservation);
        jPReservation.setLayout(jPReservationLayout);
        jPReservationLayout.setHorizontalGroup(
            jPReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReservationLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPReservationLayout.setVerticalGroup(
            jPReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPSanctiom.setBackground(new java.awt.Color(255, 102, 0));
        jPSanctiom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPSanctiomMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPSanctiomMouseReleased(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\ETUDE\\java\\BIBLIOTHEQUE3.0\\imageprojet\\Membre_16.png")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sanction");

        javax.swing.GroupLayout jPSanctiomLayout = new javax.swing.GroupLayout(jPSanctiom);
        jPSanctiom.setLayout(jPSanctiomLayout);
        jPSanctiomLayout.setHorizontalGroup(
            jPSanctiomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSanctiomLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPSanctiomLayout.setVerticalGroup(
            jPSanctiomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTab_bord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPMembre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPEmprunt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPLivre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPReservation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPSanctiom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPTab_bord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPEmprunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPMembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPSanctiom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel13.setFont(new java.awt.Font("Nyala", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("GESTION DE BIBLIOTHEQUE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jDesktopPane2.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jPTab_bordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPTab_bordMouseClicked
        // TODO add your handling code here:
        //EVEENEMT ONE CLICK........................
         setcolor(jPTab_bord);
        resetcolor(jPLivre);
        resetcolor(jPMembre);
        resetcolor(jPEmprunt);
        resetcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormTAB tab = new FormTAB();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);

    }//GEN-LAST:event_jPTab_bordMouseClicked

    private void jPTab_bordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPTab_bordMousePressed
        // TODO add your handling code here:
        setcolor(jPTab_bord);
        resetcolor(jPLivre);
        resetcolor(jPMembre);
        resetcolor(jPEmprunt);
        resetcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormTAB tab = new FormTAB();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPTab_bordMousePressed

    private void jPLivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPLivreMouseClicked
        // TODO add your handling code here:
        resetcolor(jPTab_bord);
        setcolor(jPLivre);
        resetcolor(jPMembre);
        resetcolor(jPEmprunt);
        resetcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormAjoutLivre tab = new FormAjoutLivre();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPLivreMouseClicked

    private void jPLivreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPLivreMousePressed
        // TODO add your handling code here:
        resetcolor(jPTab_bord);
        setcolor(jPLivre);
        resetcolor(jPMembre);
        resetcolor(jPEmprunt);
        resetcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormTAB tab = new FormTAB();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPLivreMousePressed

    private void jPEmpruntMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEmpruntMousePressed
        // TODO add your handling code here:
        resetcolor(jPTab_bord);
        resetcolor(jPLivre);
        resetcolor(jPMembre);
        setcolor(jPEmprunt);
        resetcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormTAB tab = new FormTAB();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPEmpruntMousePressed

    private void jPMembreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPMembreMousePressed
        // TODO add your handling code here:
        resetcolor(jPTab_bord);
        resetcolor(jPLivre);
        setcolor(jPMembre);
        resetcolor(jPEmprunt);
        resetcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormTAB tab = new FormTAB();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPMembreMousePressed

    private void jPReservationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPReservationMousePressed
        // TODO add your handling code here:
       //zay misy set ampitovina @ ery ambony......
        resetcolor(jPTab_bord);
        resetcolor(jPLivre);
        resetcolor(jPMembre);
        resetcolor(jPEmprunt);
        setcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormTAB tab = new FormTAB();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPReservationMousePressed

    private void jPEmpruntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEmpruntMouseClicked
        // TODO add your handling code here:
        //zay misy set ampitovina @ ery ambony......
        resetcolor(jPTab_bord);
        resetcolor(jPLivre);
        resetcolor(jPMembre);
        setcolor(jPEmprunt);
        resetcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormAjoutEmprunt tab = new FormAjoutEmprunt();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPEmpruntMouseClicked

    private void jPMembreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPMembreMouseClicked
        // TODO add your handling code here:
        //zay misy set ampitovina @ ery ambony......
        resetcolor(jPTab_bord);
        resetcolor(jPLivre);
        setcolor(jPMembre);
        resetcolor(jPEmprunt);
        resetcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormAjoutMembre tab = new FormAjoutMembre();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPMembreMouseClicked

    private void jPReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPReservationMouseClicked
        // TODO add your handling code here:
        resetcolor(jPTab_bord);
        resetcolor(jPLivre);
        resetcolor(jPMembre);
        resetcolor(jPEmprunt);
        setcolor(jPReservation);
        resetcolor(jPSanctiom);
        FormAjoutReservation tab = new FormAjoutReservation();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPReservationMouseClicked

    private void jPSanctiomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSanctiomMouseClicked
        // TODO add your handling code here:
        resetcolor(jPTab_bord);
        resetcolor(jPLivre);
        resetcolor(jPMembre);
        resetcolor(jPEmprunt);
        resetcolor(jPReservation);
        setcolor(jPSanctiom);
        FormTAB tab = new FormTAB();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPSanctiomMouseClicked

    private void jPSanctiomMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSanctiomMouseReleased
        // TODO add your handling code here:
        resetcolor(jPTab_bord);
        resetcolor(jPLivre);
        resetcolor(jPMembre);
        resetcolor(jPEmprunt);
        resetcolor(jPReservation);
        setcolor(jPSanctiom);
        FormTAB tab = new FormTAB();
        jDesktopPane2.removeAll();
        jDesktopPane2.add(tab).setVisible(true);
    }//GEN-LAST:event_jPSanctiomMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }
    
    //CODE MIFANDRAY @ LE SETCOLOR ANY AMBONY............................
    //le clikena......
    void setcolor(JPanel panel){
        panel.setBackground(new Color(173,185,170));
        
    }
    //le tsy clikena.......
    void resetcolor(JPanel panel){
        panel.setBackground(new Color(255,102,0));
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPEmprunt;
    private javax.swing.JPanel jPLivre;
    private javax.swing.JPanel jPMembre;
    private javax.swing.JPanel jPReservation;
    private javax.swing.JPanel jPSanctiom;
    private javax.swing.JPanel jPTab_bord;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
